server:  
  port: ${PORT:3333}

spring:
  application:
    name: customer-service
  cloud:
    service-registry:
      auto-registration:
        enabled: false  
       
  boot:
    admin:
      client:
        url:
        - http://myadmin-console-india:9001
        enabled: false
    

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
      
eureka:        
  client:
    serviceUrl:
      defaultZone: http://eureka-south-india:7001/eureka/

      
 
      
  
      
           
 
 
