server:  
  port: ${PORT:3333}

spring:
  application:
    name: customer-service
  cloud:
    service-registry:
      auto-registration:
        enabled: false  
       
  boot:
    admin:
      client:
        url:
        - http://myadmin-console-india:9001
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/customer-service?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpassword
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
    

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    health:
      show-details: always
      
eureka:        
  client:
    serviceUrl:
      defaultZone: http://eureka-south-india:7001/eureka/

      
 
      
  
      
           
 
 
