server:
  port: ${PORT:2222}

spring:
  application:
    name: account-service
  cloud:
    service-registry:
      auto-registration:
        enabled: false

  boot:
    admin:
      client:
        url:
          - http://myadmin-console-india:9001
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/account-service?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpassword
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update


eureka:
  client:
    enabled: false
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka-east-india:7003/eureka
  server:
    wait-time-in-ms-when-sync-empty: 0


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

  endpoint:
    health:
      show-details: always

# @EnableDiscoveryClient you have to set all of the following properties in application.properties to disable the service registration
# spring.cloud.service-registry.auto-registration.enabled=false
# eureka.client.enabled=false 

